#!/usr/bin/env bash
# pc-harness installer — idempotent. A second run prints "no changes".
# Never touches secrets/, log/, backups/ or an existing config.env.
set -uo pipefail
HARNESS_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
# shellcheck source=/dev/null
. "$HARNESS_DIR/bin/env.sh"

DEV=0
for a in "$@"; do
  case "$a" in
    --dev) DEV=1;;
    -h|--help) echo "usage: install.sh [--dev]   (--dev also installs the QA tools of GH19)"; exit 0;;
    *) echo "install.sh: unknown option $a" >&2; exit 2;;
  esac
done

changes=0
note() { echo "  $*"; changes=$((changes + 1)); }
skip() { [ "${VERBOSE:-0}" = 1 ] && echo "  = $*"; return 0; }

## 1. Prerequisites -----------------------------------------------------------
echo "1. prerequisites"
missing=""
for t in python3 jq systemctl; do
  command -v "$t" >/dev/null || missing="$missing $t"
done
[ -n "$missing" ] && { echo "  MISSING required:$missing" >&2; exit 1; }
systemctl --user show-environment >/dev/null 2>&1 || {
  echo "  systemd --user is not reachable (no user session)" >&2; exit 1; }
for t in tmux ydotoold docker git; do
  command -v "$t" >/dev/null || echo "  advisory: $t not found — some features are unavailable"
done
echo "  ok python3 jq systemd --user"

## 2. config.env --------------------------------------------------------------
echo "2. config"
if [ -r "$HARNESS_CONFIG" ]; then
  skip "config: $HARNESS_CONFIG"
else
  mkdir -p "$(dirname "$HARNESS_CONFIG")"
  { echo "# pc-harness configuration for this machine — generated by install.sh $(date +%F)."
    echo "HARNESS_HOST=$(hostname -s)"
    [ -n "${HARNESS_AGENT:-}" ] && echo "HARNESS_AGENT=$HARNESS_AGENT"
  } >"$HARNESS_CONFIG"
  chmod 600 "$HARNESS_CONFIG"
  note "created $HARNESS_CONFIG (see config.example.env for every key)"
  if [ -t 0 ]; then
    printf '  owner name  [%s]: ' "$(git config user.name 2>/dev/null)"; read -r v
    [ -n "$v" ] && echo "HARNESS_OWNER_NAME=$v" >>"$HARNESS_CONFIG"
    printf '  owner email [%s]: ' "$(git config user.email 2>/dev/null)"; read -r v
    [ -n "$v" ] && echo "HARNESS_OWNER_EMAIL=$v" >>"$HARNESS_CONFIG"
    printf '  ntfy topic  (blank to skip pushes): '; read -r v
    if [ -n "$v" ]; then
      mkdir -p "$(dirname "$NTFY_ENV_FILE")"; chmod 700 "$(dirname "$NTFY_ENV_FILE")"
      echo "NTFY_TOPIC=$v" >"$NTFY_ENV_FILE"; chmod 600 "$NTFY_ENV_FILE"
      note "wrote $NTFY_ENV_FILE"
    fi
  fi
  # shellcheck source=/dev/null
  . "$HARNESS_DIR/bin/env.sh"
fi

## 3. Commands on PATH --------------------------------------------------------
# bin/ holds three kinds of file: harness commands, `pc` subcommands (pc-*, dispatched by `pc`,
# never called directly) and libraries (*.sh, *.py). Only the first kind goes on PATH.
echo "3. commands -> ~/.local/bin"
mkdir -p "$HOME/.local/bin"
for f in "$HARNESS_DIR"/bin/*; do
  [ -f "$f" ] && [ -x "$f" ] || continue
  n="$(basename "$f")"
  case "$n" in pc-*|*.sh|*.py) continue;; esac
  t="$HOME/.local/bin/$n"
  if [ "$(readlink -f "$t" 2>/dev/null)" = "$(readlink -f "$f")" ]; then skip "$n"; continue; fi
  ln -sfn "$f" "$t"; note "linked $n"
done
case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) echo "  advisory: ~/.local/bin is not on PATH";; esac

## 4. systemd units and the roster --------------------------------------------
echo "4. units + roster"
UD="$HOME/.config/systemd/user"
mkdir -p "$UD"
reload=0
for u in "$HARNESS_DIR"/units/*; do
  n="$(basename "$u")"
  cmp -s "$u" "$UD/$n" && { skip "$n"; continue; }
  cp "$u" "$UD/$n"; note "installed unit $n"; reload=1
done

roster_units=""
for d in "$HARNESS_DIR"/*/; do
  [ -r "$d/BRIEF.md" ] && [ -r "$d/agent.env" ] || continue
  name="$(basename "$d")"
  SCHEDULE=""; ENABLED=no
  # shellcheck source=/dev/null
  . "$d/agent.env"
  [ -n "$SCHEDULE" ] || { echo "  $name: no SCHEDULE= in agent.env, left alone"; continue; }
  dd="$UD/agent@$name.timer.d"
  cur="$(sed -n 's/^OnCalendar=\(..*\)/\1/p' "$dd/schedule.conf" 2>/dev/null | tail -1)"
  if [ "$cur" != "$SCHEDULE" ]; then
    systemd-analyze calendar "$SCHEDULE" >/dev/null || { echo "  $name: invalid SCHEDULE '$SCHEDULE'" >&2; continue; }
    mkdir -p "$dd"
    printf '[Timer]\nOnCalendar=\nOnCalendar=%s\n' "$SCHEDULE" >"$dd/schedule.conf"
    note "schedule $name = $SCHEDULE"; reload=1
  else
    skip "schedule $name"
  fi
  [ "$ENABLED" = yes ] && roster_units="$roster_units agent@$name.timer"
done

# Units this repo ships that are not agent templates: enable them alongside the roster.
for u in "$HARNESS_DIR"/units/*.timer "$HARNESS_DIR"/units/*.service; do
  n="$(basename "$u")"
  case "$n" in agent@*) continue;; esac
  case "$n" in *.timer) roster_units="$roster_units $n";;
                 *) grep -q '^\[Install\]' "$u" && roster_units="$roster_units $n";;
  esac
done

[ "$reload" = 1 ] && { systemctl --user daemon-reload; note "daemon-reload"; }
for u in $roster_units; do
  case "$(systemctl --user is-enabled "$u" 2>/dev/null)" in
    enabled|enabled-runtime) skip "enabled $u"; continue;;
  esac
  systemctl --user enable --now "$u" >/dev/null 2>&1 && note "enabled $u" \
    || echo "  could not enable $u" >&2
done

## 5. Generated machine facts -------------------------------------------------
echo "5. KB/machine.md"
facts="$HARNESS_DIR/KB/machine.md"
tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
if "$HARNESS_DIR/bin/pc" status --facts >"$tmp" 2>/dev/null && [ -s "$tmp" ]; then
  # The header carries a generation timestamp; compare only the body so a re-run is a no-op.
  if [ -r "$facts" ] && [ "$(grep -v '^# Machine facts (generated' "$tmp")" = "$(grep -v '^# Machine facts (generated' "$facts")" ]; then
    skip "KB/machine.md up to date"
  else
    cp "$tmp" "$facts"; note "regenerated KB/machine.md"
  fi
else
  echo "  could not run pc status --facts — KB/machine.md left as is"
fi

## 6. Agent adapter -----------------------------------------------------------
echo "6. adapter"
agent="${HARNESS_AGENT:-}"
if [ -z "$agent" ]; then
  for c in claude codex gemini opencode; do command -v "$c" >/dev/null && { agent="$c"; break; }; done
  [ -n "$agent" ] && echo "  HARNESS_AGENT is unset; detected '$agent'"
fi
if [ -n "$agent" ] && [ -x "$HARNESS_DIR/adapters/$agent/install" ]; then
  out="$("$HARNESS_DIR/adapters/$agent/install")"; rc=$?
  printf '%s\n' "$out" | sed 's/^/  /'
  printf '%s' "$out" | grep -q 'no changes' || changes=$((changes + 1))
  [ "$rc" = 0 ] || echo "  adapter $agent exited $rc" >&2
else
  echo "  no adapter to install (HARNESS_AGENT='${agent}')"
fi

## 7. Optional QA tooling -----------------------------------------------------
if [ "$DEV" = 1 ]; then
  echo "7. dev tools"
  command -v shellcheck >/dev/null || echo "  install with: sudo apt install shellcheck"
  command -v shfmt >/dev/null || echo "  install with: sudo apt install shfmt"
  command -v lizard >/dev/null || echo "  install with: pipx install lizard"
  command -v jscpd >/dev/null || echo "  install with: npm install -g jscpd   (nvm node; not on PATH in non-login shells)"
  echo "  metrics: bin/tests/qa-metrics.sh [--baseline]"
fi

## 8. Verdict -----------------------------------------------------------------
echo
[ "$changes" = 0 ] && echo "install.sh: no changes" || echo "install.sh: $changes change(s) applied"
echo
"$HARNESS_DIR/bin/pc" doctor --quick
